M48
; DRILL file {KiCad (6.0.2-0)} date 2022 May 09, Monday 22:27:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-09T22:27:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.3821Y-2.1071
X3.6096Y-2.1071
T2
X3.0224Y-2.0469
X3.9673Y-2.0469
T3
X2.7469Y-2.8343
X8.2587Y-3.1492
T0
M30
