M48
; DRILL file {KiCad (6.0.0-0)} date 2022 January 14, Friday 12:57:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-14T12:57:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.3811Y-2.0547
X3.6087Y-2.0547
T2
X3.0224Y-2.0469
X3.9673Y-2.0469
T3
X2.7469Y-2.8343
X8.2587Y-3.1492
T0
M30
